version: '3.7'

services:
  spring-connect:
    build: .
    container_name: connect-backend
    ports:
      - 8082:8082
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:6.2.4-alpine
    container_name: connect-backend-redis

  postgres:
    image: postgres:13.3-alpine
    container_name: connect-backend-postgresql
    environment:
      - POSTGRES_DB=connect
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
