server:
  port: 8082

redis:
  host-name: connect-backend-redis

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://connect-backend-postgresql:5432/connect