server:
  port: 8082

redis:
  host-name: localhost

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    username: glaze
    password: straightdalmatian
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/connect